In [35]:
import pandas as pd
import numpy as np

In [36]:
df=pd.read_csv("C:/Users/Dell/Downloads/customer.csv")

In [37]:
df.sample(5)

    age  gender   review education purchased
26   53  Female     Poor        PG        No
29   83  Female  Average        UG       Yes
2    70  Female     Good        PG        No
11   74    Male     Good        UG       Yes
22   18  Female     Poor        PG       Yes

In [38]:
df = df.iloc[:,2:]

In [39]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [41]:
X_train

     review education
48     Good        UG
2      Good        PG
38     Good    School
47     Good        PG
12     Poor    School
1      Poor        UG
28     Poor    School
14     Poor        PG
25     Good    School
24  Average        PG
32  Average        UG
13  Average    School
46     Poor        PG
31     Poor    School
16     Poor        UG
49     Good        UG
43     Poor        PG
30  Average        UG
40     Good    School
5   Average    School
45     Poor        PG
29  Average        UG
6      Good    School
3      Good        PG
4   Average        UG
36     Good        UG
26     Poor        PG
37  Average        PG
27     Poor        PG
17     Poor        UG
10     Good        UG
9      Good        UG
21  Average        PG
15     Poor        UG
42     Good        PG
23     Good    School
18     Good    School
11     Good        UG
35     Poor    School
0   Average    School

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [43]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [44]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [45]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [46]:
X_train

array([[2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [1., 0.]])

In [47]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [48]:
from sklearn.preprocessing import LabelEncoder

In [49]:
le=LabelEncoder()

In [50]:
le.fit(y_train)

LabelEncoder()

In [51]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [52]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [53]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])